create table if not exists public.proyecto_resumen_ia (
  id bigint generated by default as identity primary key,
  encuesta_id bigint not null references public.encuesta(id) on delete cascade,
  proyecto_id bigint not null references public.proyecto(id) on delete cascade,
  proyecto_nombre text not null,
  equipo_nombre text,
  resumen text not null,
  fortalezas text[] not null default '{}',
  mejoras text[] not null default '{}',
  sentimiento text not null check (sentimiento in ('positivo', 'mixto', 'critico', 'insuficiente')),
  temas text[] not null default '{}',
  total_comentarios integer not null default 0,
  modelo text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint proyecto_resumen_ia_unico unique (encuesta_id, proyecto_id)
);

create index if not exists proyecto_resumen_ia_encuesta_idx on public.proyecto_resumen_ia(encuesta_id);
create index if not exists proyecto_resumen_ia_proyecto_idx on public.proyecto_resumen_ia(proyecto_id);

alter table public.proyecto_resumen_ia enable row level security;

drop policy if exists proyecto_resumen_ia_service_role_select on public.proyecto_resumen_ia;
drop policy if exists proyecto_resumen_ia_service_role_insert on public.proyecto_resumen_ia;
drop policy if exists proyecto_resumen_ia_service_role_update on public.proyecto_resumen_ia;
drop policy if exists proyecto_resumen_ia_service_role_delete on public.proyecto_resumen_ia;

create policy proyecto_resumen_ia_service_role_select
  on public.proyecto_resumen_ia
  for select
  to service_role
  using (true);

create policy proyecto_resumen_ia_service_role_insert
  on public.proyecto_resumen_ia
  for insert
  to service_role
  with check (true);

create policy proyecto_resumen_ia_service_role_update
  on public.proyecto_resumen_ia
  for update
  to service_role
  using (true)
  with check (true);

create policy proyecto_resumen_ia_service_role_delete
  on public.proyecto_resumen_ia
  for delete
  to service_role
  using (true);

grant select, insert, update, delete on table public.proyecto_resumen_ia to service_role;
grant usage, select on sequence public.proyecto_resumen_ia_id_seq to service_role;
