create table if not exists public.premio (
  id bigint generated by default as identity primary key,
  evento_id bigint references public.evento(id) on delete cascade,
  competicion_id bigint references public.competicion(id) on delete cascade,
  tipo text not null check (tipo in ('cash', 'trophy', 'recognition', 'sponsor', 'other')),
  descripcion text not null,
  posicion integer not null check (posicion > 0),
  condiciones_entrega text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint premio_unico_alcance check (
    (evento_id is not null and competicion_id is null)
    or (evento_id is null and competicion_id is not null)
  )
);

create index if not exists premio_evento_id_idx on public.premio(evento_id);
create index if not exists premio_competicion_id_idx on public.premio(competicion_id);
create index if not exists premio_posicion_idx on public.premio(posicion);

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.premio to service_role;
grant usage, select on sequence public.premio_id_seq to service_role;
